[[[0,"c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\service_identity\\__init__.py","","",null,0],[false,[["CertificateError",3,2,["CertificateError",[0,"c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]],["SubjectAltNameWarning",3,2,["SubjectAltNameWarning",[0,"c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]],["VerificationError",3,2,["VerificationError",[0,"c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]],["__title__",1,13,null],["__author__",1,13,null],["__license__",1,13,null],["__copyright__",1,13,null],["__all__",1,13,null],["__getattr__",1,12,null]]]],[[0,"c:\\Users\\Administrator\\anaconda3\\Lib\\site-packages\\service_identity\\__init__.py","","",null,0],[false,[["CertificateError",3,2,["CertificateError",[0,"c:\\Users\\Administrator\\anaconda3\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]],["SubjectAltNameWarning",3,2,["SubjectAltNameWarning",[0,"c:\\Users\\Administrator\\anaconda3\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]],["VerificationError",3,2,["VerificationError",[0,"c:\\Users\\Administrator\\anaconda3\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]]]]]]